### PR TITLE
remove unnecessary curl code

### PR DESCRIPTION
**Pull request by pierrewuethrich**

### CODE REVIEW

**Comment by pierrewuethrich** [comment]
Understood

**Comment by takerfume** [comment]
>Understood. where should the teacher_policy come from in this case to keep consistency?
@pierrewuethrich 
[Here](https://github.com/DeepX-inc/machina/blob/66719a0b81c1e91ff9298b174affa577055255de/tests/test_algos.py#L491-L493) it is.

You have to remove this line. Because you remove `curl` command, travis cannot find the pol file.

**Comment by pierrewuethrich** [comment]
Why completely remove? I think it might be better to comment it those lines out or the user might get confused about how/where to load the teacher_policy

**Comment by pierrewuethrich** [comment]
Got it

**Pull request merged**
